name: Upload coverage reports to Codecov

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov scikit-learn tensorflow scipy pillow opencv-python matplotlib

    - name: Find SnakeAI modules
      id: find-snakeai
      run: |
        files=$(grep -rl 'class SnakeAI' . | grep '\.py$')
        if [ -n "$files" ]; then
          snakeai_files=$(echo "$files" | sed 's/\.py$//;s/\.\///g' | paste -sd "," -)
          echo "snakeai_files=${snakeai_files}" >> $GITHUB_ENV
          echo "Found SnakeAI modules: ${snakeai_files}.py"
        else
          echo "Error: SnakeAI module not found"
          exit 1
        fi

    - name: Run tests with coverage
      env:
        snakeai_files: ${{ env.snakeai_files }}
      run: |
        IFS=',' read -r -a snakeai_files_array <<< "${snakeai_files}"
        for snakeai_file in "${snakeai_files_array[@]}"; do
          echo "Running tests for: $snakeai_file"
          SNAKEAI_MODULE=$snakeai_file PYTHONPATH=$PYTHONPATH:. pytest --cov=./ tests/
        done

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}


