name: Upload coverage reports to Codecov

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov scikit-learn

    - name: Find SnakeAI modules
      id: find-snakeai
      run: |
        files=$(grep -rl 'class SnakeAI' . | grep '\.py$')
        if [ -n "$files" ]; then
          for file in $files; do
            snakeai_file=$(echo $file | sed 's/\.py$//')
            snakeai_file=${snakeai_file#./}
            echo "snakeai_file=${snakeai_file}" >> $GITHUB_ENV
            echo "Found SnakeAI module: ${snakeai_file}.py"
          done
        else
          echo "Error: SnakeAI module not found"
          exit 1
        fi

    - name: Run tests with coverage
      run: |
        for snakeai_file in ${snakeai_file}; do
          echo "Running tests for: $snakeai_file"
          SNAKEAI_MODULE=$snakeai_file pytest --cov=./ tests/
        done

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
